# Klasifikasi Survei Penggunaan Belajar Online
## 1. Import Library

In [226]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler, LabelEncoder
from sklearn.impute import SimpleImputer
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

df = pd.read_csv("Survei Penggunaan Platform Belajar Online pada Mahasiswa (Jawaban) - Form Responses 1.csv")
df.head()

,Timestamp,Nama lengkap,Asal universitas (cantumkan nama lengkap),Jurusan / program studi,Angkatan,Usia Anda?,Status/aktivitas utama Anda saat ini?,Platform Utama belajar online yang paling sering Anda gunakan?,Perangkat yang paling sering Anda gunakan untuk belajar online?,Rata-rata berapa jam per minggu Anda menggunakan platform belajar online?,Tujuan utama Anda menggunakan platform belajar online?,Jenis materi yang paling Anda sukai saat belajar online?,"Menurut Anda, berapa persentase materi/kursus/modul yang biasanya Anda selesaikan?",Seberapa puas Anda terhadap platform belajar online yang paling sering Anda gunakan?
0,08/04/2026 22:24:53,Fizar Erlansyah,Universitas Pembangunan Jaya,Sistem Informasi,2024,18–24 tahun,Mahasiswa/pelajar,YouTube,Laptop,1–3 jam,Pengembangan karier,Campuran keduanya,81–100%,7
1,08/04/2026 22:27:50,Muhammad Rayhan Mumtaz,Universitas Pembangunan Jaya,Sistem Informasi,2024,18–24 tahun,Mahasiswa/pelajar,YouTube,Laptop,4–6 jam,Keperluan akademik,Campuran keduanya,81–100%,8
2,08/04/2026 22:28:25,Panji Kurnia Akbar,Universitas Pembangunan Jaya,Sistem Informasi,2024,18–24 tahun,Mahasiswa/pelajar,YouTube,Laptop,4–6 jam,Upgrade skill,Video,81–100%,8
3,08/04/2026 22:31:25,Azkiyah zhafirah,Universitas Pancasila,Farmasi,2025,18–24 tahun,Mahasiswa/pelajar,YouTube,HP / Mobile,7–10 jam,Keperluan akademik,Campuran keduanya,41–60%,7
4,08/04/2026 22:32:42,zavira verga,Universitas Pembangunan Jaya,accounting,2025,18–24 tahun,Mahasiswa/pelajar,YouTube,Laptop,Lebih dari 20 jam,Keperluan akademik,Video,81–100%,9

## 2. Cek Nama Kolom

In [227]:
df.columns.tolist()

['Timestamp',
 'Nama lengkap',
 'Asal universitas (cantumkan nama lengkap)',
 'Jurusan / program studi',
 'Angkatan',
 'Usia Anda?',
 'Status/aktivitas utama Anda saat ini?',
 'Platform Utama belajar online yang paling sering Anda gunakan?',
 'Perangkat yang paling sering Anda gunakan untuk belajar online?',
 'Rata-rata berapa jam per minggu Anda menggunakan platform belajar online?',
 'Tujuan utama Anda menggunakan platform belajar online?',
 'Jenis materi yang paling Anda sukai saat belajar online?',
 'Menurut Anda, berapa persentase materi/kursus/modul yang biasanya Anda selesaikan?',
 'Seberapa puas Anda terhadap platform belajar online yang paling sering Anda gunakan?']

## 3. Hapus Kolom yang Tidak Digunakan

In [228]:
df_model = df.drop(columns=[
    "Timestamp",
    "Nama lengkap",
    "Asal universitas (cantumkan nama lengkap)",
    "Jurusan / program studi",
    "Angkatan"
])

df_model.head()

,Usia Anda?,Status/aktivitas utama Anda saat ini?,Platform Utama belajar online yang paling sering Anda gunakan?,Perangkat yang paling sering Anda gunakan untuk belajar online?,Rata-rata berapa jam per minggu Anda menggunakan platform belajar online?,Tujuan utama Anda menggunakan platform belajar online?,Jenis materi yang paling Anda sukai saat belajar online?,"Menurut Anda, berapa persentase materi/kursus/modul yang biasanya Anda selesaikan?",Seberapa puas Anda terhadap platform belajar online yang paling sering Anda gunakan?
0,18–24 tahun,Mahasiswa/pelajar,YouTube,Laptop,1–3 jam,Pengembangan karier,Campuran keduanya,81–100%,7
1,18–24 tahun,Mahasiswa/pelajar,YouTube,Laptop,4–6 jam,Keperluan akademik,Campuran keduanya,81–100%,8
2,18–24 tahun,Mahasiswa/pelajar,YouTube,Laptop,4–6 jam,Upgrade skill,Video,81–100%,8
3,18–24 tahun,Mahasiswa/pelajar,YouTube,HP / Mobile,7–10 jam,Keperluan akademik,Campuran keduanya,41–60%,7
4,18–24 tahun,Mahasiswa/pelajar,YouTube,Laptop,Lebih dari 20 jam,Keperluan akademik,Video,81–100%,9

## 4. Ubah Nama Kolom agar Lebih Ringkas

In [229]:
df_model = df_model.rename(columns={
    "Usia Anda?": "usia",
    "Status/aktivitas utama Anda saat ini?": "status",
    "Platform Utama belajar online yang paling sering Anda gunakan?": "platform",
    "Perangkat yang paling sering Anda gunakan untuk belajar online?": "perangkat",
    "Rata-rata berapa jam per minggu Anda menggunakan platform belajar online?": "jam_belajar",
    "Tujuan utama Anda menggunakan platform belajar online?": "tujuan",
    "Jenis materi yang paling Anda sukai saat belajar online?": "jenis_materi",
    "Menurut Anda, berapa persentase materi/kursus/modul yang biasanya Anda selesaikan?": "persentase_selesai",
    "Seberapa puas Anda terhadap platform belajar online yang paling sering Anda gunakan?": "kepuasan"
})

df_model.head()

,usia,status,platform,perangkat,jam_belajar,tujuan,jenis_materi,persentase_selesai,kepuasan
0,18–24 tahun,Mahasiswa/pelajar,YouTube,Laptop,1–3 jam,Pengembangan karier,Campuran keduanya,81–100%,7
1,18–24 tahun,Mahasiswa/pelajar,YouTube,Laptop,4–6 jam,Keperluan akademik,Campuran keduanya,81–100%,8
2,18–24 tahun,Mahasiswa/pelajar,YouTube,Laptop,4–6 jam,Upgrade skill,Video,81–100%,8
3,18–24 tahun,Mahasiswa/pelajar,YouTube,HP / Mobile,7–10 jam,Keperluan akademik,Campuran keduanya,41–60%,7
4,18–24 tahun,Mahasiswa/pelajar,YouTube,Laptop,Lebih dari 20 jam,Keperluan akademik,Video,81–100%,9

## 4.1 Cek Missing Values Awal

In [ ]:
print(df_model.isna().sum())

usia                  0
status                0
platform              0
perangkat             0
jam_belajar           0
tujuan                0
jenis_materi          0
persentase_selesai    0
kepuasan              0
dtype: int64

## 4.2 Mapping Jam Belajar ke Nilai Numerik

In [ ]:
map_jam = {
    "1–3 jam": 2,
    "4–6 jam": 5,
    "7–10 jam": 8.5,
    "11–15 jam": 13,
    "16–20 jam": 18,
    "Lebih dari 20 jam": 22  # asumsi
}

df_model["jam_belajar_num"] = df_model["jam_belajar"].map(map_jam)

## 4.3 Mapping Persentase Selesai ke Nilai Numerik

In [ ]:
map_persen = {
    "0–20%": 10,
    "21–40%": 30,
    "41–60%": 50,
    "61–80%": 70,
    "81–100%": 90
}

df_model["persentase_selesai_num"] = df_model["persentase_selesai"].map(map_persen)

## 4.4 Membuat Kelas Kepuasan

In [ ]:
df_model["kepuasan"] = pd.to_numeric(df_model["kepuasan"], errors="coerce")

def kategori_kepuasan(x):
    if x <= 5:
        return "Rendah"
    elif x <= 7:
        return "Sedang"
    else:
        return "Tinggi"

df_model["kelas_kepuasan"] = df_model["kepuasan"].apply(kategori_kepuasan)
df_model[["jam_belajar", "jam_belajar_num",
          "persentase_selesai", "persentase_selesai_num",
          "kepuasan", "kelas_kepuasan"]].head()

,jam_belajar,jam_belajar_num,persentase_selesai,persentase_selesai_num,kepuasan,kelas_kepuasan
0,1–3 jam,2.0,81–100%,90,7,Sedang
1,4–6 jam,5.0,81–100%,90,8,Tinggi
2,4–6 jam,5.0,81–100%,90,8,Tinggi
3,7–10 jam,8.5,41–60%,50,7,Sedang
4,Lebih dari 20 jam,22.0,81–100%,90,9,Tinggi

## 4.5 Menentukan Fitur dan Target

In [ ]:
X = df_model[[
    "usia",
    "status",
    "platform",
    "perangkat",
    "tujuan",
    "jenis_materi",
    "jam_belajar_num",
    "persentase_selesai_num"
]].copy()

y = df_model["kelas_kepuasan"]

## 4.6 Memisahkan Fitur Kategori dan Numerik

In [ ]:
categorical_features = [
    "usia",
    "status",
    "platform",
    "perangkat",
    "tujuan",
    "jenis_materi"
]

numeric_features = [
    "jam_belajar_num",
    "persentase_selesai_num"
]

In [236]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

# Transformer kategori
categorical_transformer = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("onehot", OneHotEncoder(handle_unknown="ignore"))
])

# Transformer numerik
numeric_transformer = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())
])

preprocessor = ColumnTransformer(
    transformers=[
        ("cat", categorical_transformer, categorical_features),
        ("num", numeric_transformer, numeric_features)
    ]
)

## 5. Bagi Data Train dan Test

In [237]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

print("Jumlah data train:", len(X_train))
print("Jumlah data test :", len(X_test))

Jumlah data train: 20
Jumlah data test : 5

## 6. Model Decision Tree

In [238]:
dt_model = Pipeline(steps=[
    ("preprocessor", preprocessor),
    ("classifier", DecisionTreeClassifier(random_state=42, max_depth=4))
])

dt_model.fit(X_train, y_train)
y_pred_dt = dt_model.predict(X_test)

print("=== Decision Tree ===")
print("Accuracy:", accuracy_score(y_test, y_pred_dt))
print("\nClassification Report:\n", classification_report(y_test, y_pred_dt))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred_dt))

=== Decision Tree ===
Accuracy: 0.6

Classification Report:
               precision    recall  f1-score   support

      Sedang       0.50      1.00      0.67         2
      Tinggi       1.00      0.33      0.50         3

    accuracy                           0.60         5
   macro avg       0.75      0.67      0.58         5
weighted avg       0.80      0.60      0.57         5


Confusion Matrix:
 [[2 0]
 [2 1]]

## 7. Model K-Nearest Neighbors (KNN)

In [239]:
knn_model = Pipeline(steps=[
    ("preprocessor", preprocessor),
    ("classifier", KNeighborsClassifier(n_neighbors=3))
])

knn_model.fit(X_train, y_train)
y_pred_knn = knn_model.predict(X_test)

print("=== KNN ===")
print("Accuracy:", accuracy_score(y_test, y_pred_knn))
print("\nClassification Report:\n", classification_report(y_test, y_pred_knn))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred_knn))

=== KNN ===
Accuracy: 0.4

Classification Report:
               precision    recall  f1-score   support

      Rendah       0.00      0.00      0.00         0
      Sedang       0.50      1.00      0.67         2
      Tinggi       0.00      0.00      0.00         3

    accuracy                           0.40         5
   macro avg       0.17      0.33      0.22         5
weighted avg       0.20      0.40      0.27         5


Confusion Matrix:
 [[0 0 0]
 [0 2 0]
 [1 2 0]]

c:\Users\Lintar\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\Lintar\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\Lintar\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\Lintar\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\Lintar\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\Lintar\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

## 8. Perbandingan Hasil Model

In [240]:
hasil = pd.DataFrame({
    "Model": ["Decision Tree", "KNN"],
    "Accuracy": [
        accuracy_score(y_test, y_pred_dt),
        accuracy_score(y_test, y_pred_knn)
    ]
})

hasil.sort_values(by="Accuracy", ascending=False)

           Model  Accuracy
0  Decision Tree       0.6
1            KNN       0.4

## 9. Prediksi pada Data Baru

In [241]:
data_baru = pd.DataFrame([{
    "usia": "18–24 tahun",
    "status": "Mahasiswa/pelajar",
    "platform": "YouTube",
    "perangkat": "Laptop",
    "tujuan": "Keperluan akademik",
    "jenis_materi": "Video",
    "jam_belajar_num": 22,
    "persentase_selesai_num": 90
}])

prediksi = dt_model.predict(data_baru)
print("Prediksi kelas kepuasan:", prediksi[0])

Prediksi kelas kepuasan: Sedang